Create sinatra-memo-app
tksmasaki/sinatra-memo-app pull request #1
Opened 2021-08-17 09:27 UTC by tksmasaki

2021-08-23 07:16 UTC, u1tnk requested changes

2021-08-23 07:16 UTC, u1tnk commented on app/memo.rb
> +      else memo
これはなんでしょう？

2021-08-23 07:16 UTC, u1tnk commented on app/memo.rb
> +    memo_data[:memos].map! do |memo|
これでも良いのですが、例えば idから保存indexが分かれば `memo_data[:memos][index] = xxx`と普通に代入で更新できますね。
また、データ構造として hashにしてidをキーにすればもっと簡単に取得、更新できますね。

2021-08-23 07:16 UTC, u1tnk commented on app/memo.rb
> +    memo_data[:memos].find { |i| i[:id] == id }
create/updateメソッドの戻り値に編集後のデータを返す必要は無いと思います。
呼び出し元でまた必要になれば find系のメソッドで見つければ良いですし。

2021-08-23 07:16 UTC, u1tnk commented on app/app.rb
> +    redirect to('/memos')
細かい配慮までされてますね 👍

2021-08-25 03:28 UTC, tksmasaki commented on app/memo.rb
> +    memo_data[:memos].find { |i| i[:id] == id }
操作対象データを特定するためにメモのデータを返していたのですが、修正後のコミットでcreateのみ作成したメモのidを返すようにしました。update時はリクエストで指定されている:idを使うようにしています。
ご指摘いただいたように、find系のメソッドに分ける方法を考えたのですが、思いついたものとして、
- idが最新（一番数値が大きい）メモを取得するfind系メソッド

があるのですが、これだと新規作成したメモであることを保証できないと思い(ほぼ機能するとは思うのですが...)、createメソッドでidを返すようにしています。
もし、他に良い方法があれば教えていただきたいです。
ご確認よろしくお願いします🙇‍♂️

2021-08-25 03:30 UTC, tksmasaki commented on app/memo.rb
> +    memo_data[:memos].map! do |memo|
> データ構造として hashにしてidをキーにすればもっと簡単に取得、更新できますね。

アドバイスありがとうございます！
そのように修正しました。

2021-08-25 03:32 UTC, tksmasaki commented on app/memo.rb
> +      else memo
対象以外はそのまま返す意図で書いていたと思うのですが、不要なコードでした...

2021-08-27 04:12 UTC, u1tnk commented on app/memo.rb
> +    memo_data[:memos].find { |i| i[:id] == id }
> があるのですが、これだと新規作成したメモであることを保証できないと思い(ほぼ機能するとは思うのですが...)、createメソッドでidを返すようにしています。
もし、他に良い方法があれば教えていただきたいです。

良い方法だと思います。
最新の一件を取る方法でも、現在の 1サーバー、1データベースファイルなら動きますが、実際のDBを使って複数ユーザがアクセスすると保証できないですからね。

2021-08-27 04:13 UTC, u1tnk approved these changes

2021-08-27 04:38 UTC, merged